# Generated by Django 3.1.6 on 2021-02-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pureba',
            new_name='Prueba',
        ),
    ]
