# Generated by Django 3.1.6 on 2021-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de los empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Mis Empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
    ]
