# Generated by Django 3.1.6 on 2021-02-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empleados'},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='jon',
            new_name='job',
        ),
    ]
