# Generated by Django 3.1.6 on 2021-02-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nulate',
            new_name='anulate',
        ),
    ]
