# Generated by Django 3.1.6 on 2021-02-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20210211_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mis departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
    ]
