# Generated by Django 3.1.6 on 2021-02-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20210213_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='short_name',
            new_name='shor_name',
        ),
    ]
