# Generated by Django 3.1.6 on 2021-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_auto_20210225_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(max_length=20, verbose_name='Nombre corto'),
        ),
    ]
